#! /usr/bin/python3
'''
Python boilerplate imports and definition in order
to start the python interpreter console with basic
cmd definitions
'''

# Usage: launch python shell with `/usr/bin/python3 -i .pyrc`

import os
import sys
import re


class clear(object):
    '''
    something to clear the python interpreter console
    usage: >>> clear
    '''

    def __repr__(self):
        os.system('cls' if os.name == 'nt' else 'clear')
        #clear = lambda: os.system('cls' if os.name == 'nt' else 'clear')
        return ''

c = clear = clear()


class exit(object):
    '''
    something to exit the python interpreter console
    usage: >>> exit
    '''
    exit = exit     # original object

    def __repr__(self):
        self.exit() # call original
        return ''


quit = q = exit = exit()


class Prompt:
    '''
    define python shell prompt
    '''
    def __str__(self):
        pwd_text = os.getcwd()
        short_pwd_text = re.search(r"/[^/]+/[^/]+/[^/]+$", pwd_text).group(0)
        if not short_pwd_text:
            pass
        elif len(pwd_text) > len(short_pwd_text) + 3:
            pwd_text = '...' + short_pwd_text
        else:
            pass

        return '%s :>' % pwd_text


sys.ps1 = Prompt()
del sys
del Prompt
